# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MyBioCaddie
brief-intro: My Data
baseurl: "/mybiocaddie" # the subpath of your site, e.g. /blog
url: "http://cmungall.github.io/mybiocaddie" # the base hostname & protocol for your site
repository: biodatasets/mybiocaddie  # modify this

permalink: /:year/:month/:day/:title/

# other links
twitter_username: chrismungall
github_username:  cmungall
email: cjmungall@lbl.gov

collections:
  metadata:
    output: true
  ctest:
    output: true
  
description_footer: My BioCaddie!

# comments
# two ways to comment, only choose one, and use your own short name
disqus_shortname: mybiocaddie

##google_analytics_id: UA-72449510-4 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

biocaddie_categories: [Phenotype, Genotype, Exposome]

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
# note: no longer required?
#gems: [jekyll-paginate]
#paginate: 6
